listen_port: 3001

db:
    user: de
    password: testpassword
    host: db
    port: 5432
    database: de

logging:
    level: info
    label: dashboard-aggregator

permissions:
    uri: http://permissions:60005
    public_group: put-group-uuid-here

website:
    url: https://cyverse.org
    feeds:
        news: "/news/rss.xml"
        events: "/events/rss.xml"

videos:
    url: https://www.youtube.com/feeds/videos.xml?channel_id=UC-gvdjTz9rq6RovZ57LoDDA

apps:
    favorites_group_index: 1

# todo add
app-exposer:
    url: http://app-exposer
    user: dashboard-aggregator
